language: android
jdk: oraclejdk8
dist: trusty

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache

env:
    global:
        - ANDROID_API_LEVEL=28
        - ANDROID_BUILD_TOOLS_VERSION=28.0.3
        - secure: lOPVkwwXREU+FFzA1TUINigYgKbjcqPTK5wl/DWJgIUAcXkBZU4L/AkwsvUd53Y/4+ehV1JlShDLQ7nLunXr23dwy6slAUjYGR4Ljmy9oe2H/S4svEwca+hSYUqnFnwMVvSM1Mb5mD2JpceJVjIrXQ8Cdxz7NHk9qHepfy9A9sg6or4eoei/VNszGCUHyk8gmbCOAtfB6hHFE9TNcEhL8viMH05Uw3D+RksuRPdDBcx5DUA/Y+UpQ4eKmiOc9yUqaGFyHMI8S74ZfgGVdxViNtVPUOxAg1BG87C5hffKiqOM9wgEwXxqHvVreMIi3z/P57tcoUG+lvFIeAMLeyVl5daKfxtmF1+ss2HYw+Tmgu1f+FTghKxy2CtvgzY6MTV55CfdhrGQnS3ulJbdrSbrR+R+FlWjf4Nu51hxNa3HmDZbb9E4PgGXWll8Ohdlmw1ii11tjGPloCHp1m6RsZ5JOJlgpOlXYOQmZYw4CHVUkvxcrN9Ga12sdWdJc9KZbU7CgOZQyWGfxNvzPGxcbWmbihc9aOE4chjQNxEaf3wmcwLctGHn/Cyn57xyXTFle4BEcOrJ0XBWHgfDQIVH1aOvcOAe8EhB0r38322imCCVis6SNHMzVTvDQUephYVwpac8wOwB1rBFjzTdCtZDFp2zFr10z8A0vfCZZ2n8asoXhdA=
        
android:
    components:
        - tools
        - tools
        - platform-tools
        # The BuildTools version used by your project
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        # The SDK version used to compile your project
        - android-$ANDROID_API_LEVEL
        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:    
    - mkdir -p "$ANDROID_HOME/licenses"
    - 'echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"'
    - 'echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"'
    - 'openssl aes-256-cbc -K $encrypted_510cbae6f134_key -iv $encrypted_510cbae6f134_iv -in default.jks.enc -out default.jks -d'
    - 'chmod +x gradlew'
    # - './gradlew dependencies || true' 
    
script:
    - ./gradlew clean build
    
before_deploy:
    - 'cp $TRAVIS_BUILD_DIR/default.jks $HOME'
    - 'cd app/build/outputs/apk/release'
    - 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/default.jks -storepass $storepass -keypass $storepass app-release-unsigned.apk key0'
    - 'jarsigner -verify app-release-unsigned.apk'
    - '${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/zipalign -v 4 app-release-unsigned.apk AdabNightly.apk'
deploy:
    provider: releases
    file: AdabNightly.apk
    skip_cleanup: true
    on:
        repo: ambinusian/adab
        tags: true
        jdk: oraclejdk8
    api_key:
        secure: FWq7rPtxJ3ol+q5YpI5/b/6wWYjLRHjs5oyyynDLE+UjEsA5VMwVnhlVhFmz+G9TkXeQf3ukN0YTBhqWw02aM0Fd88z/t6j3SCJqGyj3UooJ5qVj0pCczU7IND83MHoC4pUNmH0EmJZ35ZqWhEhmLMkGEFpgdzYq5FPgedNsqxV24hvMZjCQ7bwmHE7IXLsSVPpCC9auYbzw3vYsuysmGS+nxdaBw2+fFk958VdZ7EEMdAxlyqiH1zKdMCOtFaiKBij5qIxCrzfa2UYHwTLhDezWnZRbZrunQHs6c7kyZGey4ihS7+eo2Gc3xYhXK2xtV5ziL0AbyVdbSkEufjeRCuxjurOGMMLzQARYZBWxH8XYK2PTO7K7FFAHZsz28VAgJH0CUG108xEIfMC+JlkNA+wk96Qrp+RE0iLE3GJhDSO4qUI+uJU0svbVom5w7F8dz9HrDv8oWX0EOTDepfoHArnw0sw2Do9vorGcP8bYhrlwMhM8AFfhkxq+67bDwAgQw/MucE6GQP+iYBfigyCxXPNKSbxZ5cJ9fTAUiYW/A1CVDpw8CWUZIRrBiDc/ay0fJ508ZwvwVJCnb19zCv1zP5RhjBaiXmyqQ77l9tIiJZOUac+kPJ5Fk44zcX6kChGwkIpOhKVlEhHwZP32aytIgMXsna/u2QS2422HLY5MViQ=

after_failure:
  # dumps the log then exits
  # - adb logcat -d